<div class = "jumbotron col-md-6">
<?php

    $title = 'Edit Task';
    $this->headTitle($title);

?>
<h2><?php echo $this->escapeHtml($title);?></h2>

<?php
    $form->setAttribute('action',$this->url('task',['action'=> 'add-task']));
    $form->prepare();
?>

<?php echo $this->form()->openTag($form);?>

<div class="form-group">    
    <?php echo $this->formHidden($form->get('id')->setAttributes(['class'=>'form-control']));?>
</div>
<div class="form-group">      
    <?php echo $this->formRow($form->get('name')->setAttributes(['class'=>'form-control']));?>
</div>
<div class="form-group">     
    <?php echo $this->formRow($form->get('description')->setAttributes(['class'=>'form-control']));?>
</div>
<div class="form-group">    
    <?php echo $this->formRow($form->get('startdate')->setAttributes(['class'=>'form-control']));?>
</div>
<div class="form-group"> 
    <?php echo $this->formRow($form->get('enddate')->setAttributes(['class'=>'form-control']));?>
</div>
<!-- <div class="form-group"> 
    <?php echo $this->formRow($form->get('status')->setAttributes(['class'=>'form-control']));?>
</div> -->
<div class="form-group"> 
    <?php echo $this->formSubmit($form->get('submit')->setAttributes(['class'=>'btn btn-submit']));?>
    </div>
<div class="form-group">     


<?php echo $this->form()->closeTag();?>
  

</div>

