
<div class="jumbotron">
<h2>ToDo</h2>
 <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>      
     <a href="<?php echo $this->basePath('task/add-task')?>" = class="btn btn-primary "> Add Task</a>
      </br></br>
      <?php foreach($tasks as $task):?>
      <tr>
            <td><?php echo $task->getName();?></td>
            <td><?php echo $task->getDescription();?></td>
            <td><?php if($task->getStatus() == 0): echo 'Incomplete'?><?php else: echo 'Completed'?><?php endif;?></td>
            <td>
            <a href="<?php echo $this->url('task',['action'=>'view-task', 'id'=> $task->getId()]);?>" class = "btn btn-succes"><i class="glyphicon glyphicon-eye-open"></i>
            </a></td>        
       
      </tr>
      <?php endforeach;?>
    </tbody>
  </table>
   


</div>


