<div class="jumbotron">

 <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>      
      <button class="btn btn-primary "> Add Task</button>
      </br></br>
      <?php foreach($tasks as $task):?>
      <tr>
            <td><?php echo $task->getName();?></td>
            <td><?php echo $task->getDescription();?></td>
            <td>
            
            </td>        
       
      </tr>
      <?php endforeach;?>
    </tbody>
  </table>
   


</div>


